# The first app
# pulled from image or could be built
app1:
    image: app1
    container_name: app1
    restart: always
    ports:
        - "127.0.0.1:3001:3001"

# A second app
app2:
    image: app2
    container_name: app2
    restart: always
    ports:
        - "127.0.0.1:3000:3000"

# Nginx serving Apps
plata-nginx:
    build: ./nginx
    links:
        - app1
        - app2
    ports:
        - "80:80"
        - "443:443"
    volumes_from:
      - plata-nginx-err-log
      - plata-nginx-access-log
      - letsencrypt-data
    restart: always
    container_name: plata-nginx

# Data container volume for error logs
plata-nginx-err-log:
    image: ubuntu
    container_name: plata-nginx-err-log
    volumes:
      - plata-nginx-err-log:/var/log/nginx/error
    command: /bin/bash

# Data container volume for access logs
plata-nginx-access-log:
    image: ubuntu
    container_name: plata-nginx-access-log
    volumes:
      - plata-nginx-access-log:/var/log/nginx/access
    command: /bin/bash
